name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: 18.x

    - run: npm install

    - run: node build.js

    - name: Create public
      run: |
        mkdir dist
        cp extensions.yml dist/extensions.yml
        cp extensions.json dist/extensions.json

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.4.1
      with:
        branch: gh-pages
        folder: dist
        clean: true
